# Mean Normalization

In machine learning we use large amounts of data to train our models. Some machine learning algorithms may require that the data is *normalized* in order to work correctly. The idea of normalization, also known as *feature scaling*, is to ensure that all the data is on a similar scale, *i.e.* that all the data takes on a similar range of values. For example, we might have a dataset that has values between 0 and 5,000. By normalizing the data we can make the range of values be between 0 and 1.

In this lab, you will be performing a different kind of feature scaling known as *mean normalization*. Mean normalization will scale the data, but instead of making the values be between 0 and 1, it will distribute the values evenly in some small interval around zero. For example, if we have a dataset that has values between 0 and 5,000, after mean normalization the range of values will be distributed in some small range around 0, for example between -3 to 3. Because the range of values are distributed evenly around zero, this guarantees that the average (mean) of all elements will be zero. Therefore, when you perform *mean normalization* your data will not only be scaled but it will also have an average of zero. 

# To Do:

You will start by importing NumPy and creating a rank 2 ndarray of random integers between 0 and 5,000 (inclusive) with 1000 rows and 20 columns. This array will simulate a dataset with a wide range of values. Fill in the code below

In [11]:
# import NumPy into Python
import numpy as np

# Create a 1000 x 20 ndarray with random integers in the half-open interval [0, 5001).
X = np.random.randint(0,5001, size=(1000, 20))

# print the shape of X
print(X)
print(X.shape)
print(X.max())
print(X.min())

[[3031 2376 2812 ... 3343 3112 1072]
 [ 214  749 2254 ... 1890  564 1191]
 [3008  994 2195 ...  702 4015 2785]
 ...
 [  50 2097 2629 ... 4439 3357 1949]
 [ 884 2483  577 ...  581 3347 3364]
 [1968 1704 3615 ... 3469 1866 4537]]
(1000, 20)
5000
0


Now that you created the array we will mean normalize it. We will perform mean normalization using the following equation:

$\mbox{Norm_Col}_i = \frac{\mbox{Col}_i - \mu_i}{\sigma_i}$

where $\mbox{Col}_i$ is the $i$th column of $X$, $\mu_i$ is average of the values in the $i$th column of $X$, and $\sigma_i$ is the standard deviation of the values in the $i$th column of $X$. In other words, mean normalization is performed by subtracting from each column of $X$ the average of its values, and then by dividing by the standard deviation of its values. In the space below, you will first calculate the average and standard deviation of each column of $X$. 

In [19]:
# Average of the values in each column of X
ave_cols = X.mean(axis=0)
print(ave_cols)

# Standard Deviation of the values in each column of X
std_cols = X.std(axis=0)
print(std_cols)


[2510.449 2452.251 2453.578 2473.174 2543.739 2430.05  2496.929 2531.143
 2450.759 2522.038 2551.726 2539.11  2449.709 2486.468 2521.566 2548.144
 2547.229 2533.653 2533.36  2529.432]
[1446.89429033 1401.49984088 1427.50294287 1466.94946461 1440.6323802
 1439.07701931 1460.4331241  1439.6574275  1447.87984064 1434.72501008
 1438.84103254 1466.7452212  1448.16845164 1434.13520178 1469.95220522
 1456.93059658 1457.36424842 1449.45350963 1442.77093345 1438.3046066 ]


If you have done the above calculations correctly, then `ave_cols` and `std_cols`, should both be vectors with shape `(20,)` since $X$ has 20 columns. You can verify this by filling the code below:

In [18]:
# Print the shape of ave_cols
print(ave_cols.shape)

# Print the shape of std_cols
print(std_cols.shape)

(20,)
(20,)


You can now take advantage of Broadcasting to calculate the mean normalized version of $X$ in just one line of code using the equation above. Fill in the code below

In [20]:
# Mean normalize X
X_norm = (X - ave_cols)/std_cols
print(X_norm)

[[ 0.35977127 -0.05440671  0.2510832  ...  0.55838079  0.40106159
  -1.01329857]
 [-1.58715741 -1.21530588 -0.13980917 ... -0.44406598 -1.36498453
  -0.93056227]
 [ 0.34387516 -1.04049316 -0.18114008 ... -1.26368524  1.02694057
   0.17768698]
 ...
 [-1.70050363 -0.25347916  0.12288731 ...  1.31452785  0.57087371
  -0.4035529 ]
 [-1.12409663  0.02194007 -1.31458783 ... -1.34716497  0.56394261
   0.58024427]
 [-0.37490576 -0.53389303  0.81360393 ...  0.64531011 -0.46255437
   1.39578778]]


If you have performed the mean normalization correctly, then the average of all the elements in $X_{\tiny{\mbox{norm}}}$ should be close to zero, and they should be evenly distributed in some small interval around zero. You can verify this by filing the code below:

In [27]:
# Print the average of all the values of X_norm
print(X_norm.mean())

# Print the average of the minimum value in each column of X_norm
print(X_norm.min(axis=0).mean())

# Print the average of the maximum value in each column of X_norm
print(X_norm.max(axis=0).mean())

1.2079226507921702e-17
-1.7304619060040523
1.7244741471695453


You should note that since $X$ was created using random integers, the above values will vary. 

# Data Separation

After the data has been mean normalized, it is customary in machine learnig to split our dataset into three sets:

1. A Training Set
2. A Cross Validation Set
3. A Test Set

The dataset is usually divided such that the Training Set contains 60% of the data, the Cross Validation Set contains 20% of the data, and the Test Set contains 20% of the data. 

In this part of the lab you will separate `X_norm` into a Training Set, Cross Validation Set, and a Test Set. Each data set will contain rows of `X_norm` chosen at random, making sure that we don't pick the same row twice. This will guarantee that all the rows of `X_norm` are chosen and randomly distributed among the three new sets.

You will start by creating a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`. You can do this by using the `np.random.permutation()` function. The `np.random.permutation(N)` function creates a random permutation of integers from 0 to `N - 1`. Let's see an example:

In [32]:
# We create a random permutation of integers 0 to 4
T = np.random.permutation(4)
print (T)

[3 2 1 0]


# To Do

In the space below create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`. You can do this in one line of code by extracting the number of rows of `X_norm` using the `shape` attribute and then passing it to the  `np.random.permutation()` function. Remember the `shape` attribute returns a tuple with two numbers in the form `(rows,columns)`.

In [72]:
# Create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`
row_indices = np.random.permutation(X_norm.shape[0])
print(row_indices.shape)
print(row_indices[:3])

(1000,)
[348 279 472]


Now you can create the three datasets using the `row_indices` ndarray to select the rows that will go into each dataset. Rememeber that the Training Set contains 60% of the data, the Cross Validation Set contains 20% of the data, and the Test Set contains 20% of the data. Each set requires just one line of code to create. Fill in the code below

In [74]:
# Make any necessary calculations.
# You can save your calculations into variables to use later.


# Create a Training Set
X_train = np.copy(X_norm[row_indices[:600],:])

# Create a Cross Validation Set
X_crossVal = np.copy(X_norm[row_indices[600:800],:])

# Create a Test Set
X_test = np.copy(X_norm[row_indices[800:],:])


If you performed the above calculations correctly, then `X_tain` should have 600 rows and 20 columns, `X_crossVal` should have 200 rows and 20 columns, and `X_test` should have 200 rows and 20 columns. You can verify this by filling the code below:

In [75]:
# Print the shape of X_train
print(X_train.shape)

# Print the shape of X_crossVal
print(X_crossVal.shape)

# Print the shape of X_test
print(X_test.shape)

(600, 20)
(200, 20)
(200, 20)
